   
uart:
  id: mod_bus
  tx_pin: 17
  rx_pin: 16
  baud_rate: 9600
  stop_bits: 1
  data_bits: 8

modbus:
  id: modbus_versati3
  uart_id: mod_bus

modbus_controller:
  - id: versati3
    address: 0x01
    modbus_id: modbus_versati3
    setup_priority: -10
    update_interval: 30s

number:
  - platform: modbus_controller
    modbus_controller_id: versati3
    id: gree_wot_heat
    name: "gree_wot_heat"
    device_class: "temperature"
    address: 10
    register_type: holding
    value_type: U_WORD
    unit_of_measurement: '°C'  

  - platform: modbus_controller
    modbus_controller_id: versati3
    id: gree_rt_heat
    name: "gree_rt_heat"
    device_class: "temperature"
    address: 12
    register_type: holding
    value_type: U_WORD
    unit_of_measurement: '°C'       

  - platform: modbus_controller
    modbus_controller_id: versati3
    id: gree_upper_wt_heat
    name: "gree_upper_wt_heat"
    device_class: "temperature"
    address: 21
    register_type: holding
    value_type: U_WORD
    unit_of_measurement: '°C'   
    
  - platform: modbus_controller
    modbus_controller_id: versati3
    id: gree_lower_wt_heat
    name: "gree_lower_wt_heat"
    device_class: "temperature"
    address: 22
    register_type: holding
    value_type: U_WORD
    unit_of_measurement: '°C'   
    
  - platform: modbus_controller
    modbus_controller_id: versati3
    id: gree_upper_at_heat
    name: "gree_upper_at_heat"
    device_class: "temperature"
    address: 17
    register_type: holding
    value_type: U_WORD
    unit_of_measurement: '°C'   
    
  - platform: modbus_controller
    modbus_controller_id: versati3
    id: gree_lower_at_heat
    name: "gree_lower_at_heat"
    device_class: "temperature"
    address: 18
    register_type: holding
    value_type: S_WORD
    unit_of_measurement: '°C'   
    
  - platform: modbus_controller
    modbus_controller_id: versati3
    id: gree_upper_rt_heat
    name: "gree_upper_rt_heat"
    device_class: "temperature"
    address: 19
    register_type: holding
    value_type: U_WORD
    unit_of_measurement: '°C'   
    
  - platform: modbus_controller
    modbus_controller_id: versati3
    id: gree_lower_rt_heat
    name: "gree_lower_rt_heat"
    device_class: "temperature"
    address: 20
    register_type: holding
    value_type: U_WORD
    unit_of_measurement: '°C'   

  - platform: modbus_controller
    modbus_controller_id: versati3
    id: gree_power_limit
    name: "gree_power_limit"
    device_class: "power"
    address: 43
    register_type: holding
    value_type: U_WORD
    unit_of_measurement: 'kW'
    
select:
  - platform: modbus_controller
    modbus_controller_id: versati3
    id: gree_mode
    name: "gree_mode"
    address: 2
    value_type: U_WORD
    optionsmap:
      "Heat": 1
      "Hot Water": 2
      "Cool + Hot Water": 3
      "Heat + Hot Water": 4
      "Cool": 5
  - platform: modbus_controller
    modbus_controller_id: versati3
    id: gree_thermostat
    name: "gree_thermostat"
    address: 39
    value_type: U_WORD
    optionsmap:
      "Without": 0
      "Air": 1
      "Air + Hot Water": 2
  - platform: modbus_controller
    modbus_controller_id: versati3
    id: gree_on_off
    name: "gree_on_off"
    address: 42
    value_type: U_WORD
    optionsmap:
      "On": 0xAA
      "Off": 0x55
  - platform: modbus_controller
    modbus_controller_id: versati3
    id: gree_status_thermostat
    name: "gree_status_thermostat"
    address: 132
    value_type: U_WORD
    optionsmap:
      "Cool": 1
      "Heat": 2
      "Off": 3

switch:
  - platform: modbus_controller
    modbus_controller_id: versati3
    id: gree_coil_ctrl_state
    name: gree_coil_ctrl_state
    register_type: coil
    address: 17
    bitmask: 1
  - platform: modbus_controller
    modbus_controller_id: versati3
    id: gree_coil_quiet_ctrl
    name: gree_coil_quiet_ctrl
    register_type: coil
    address: 21
    bitmask: 1
  - platform: modbus_controller
    modbus_controller_id: versati3
    id: gree_coil_wdwdepend
    name: gree_coil_wdepend
    register_type: coil
    address: 22
    bitmask: 1

binary_sensor:
  - platform: modbus_controller
    modbus_controller_id: versati3
    id: gree_coil_compressor_state
    name: "gree_coil_compressor_state"
    address: 80
    register_type: coil
  - platform: modbus_controller
    modbus_controller_id: versati3
    id: gree_coil_crankcase_heater_state
    name: "gree_coil_crankcase_heater_state"
    address: 84
    register_type: coil
  
sensor:
  - platform: modbus_controller
    modbus_controller_id: versati3
    id: gree_delta_heat
    name: "gree_delta_heat"
    device_class: "temperature"
    state_class: "measurement"
    address: 30
    register_type: holding
    value_type: U_WORD
    unit_of_measurement: '°C'   
    
  - platform: modbus_controller
    modbus_controller_id: versati3
    id: gree_delta_room_temp
    name: "gree_delta_room_temp"
    device_class: "temperature"
    state_class: "measurement"
    address: 32
    register_type: holding
    value_type: U_WORD
    unit_of_measurement: '°C'   

  - platform: modbus_controller
    modbus_controller_id: versati3
    id: gree_current_limit
    name: "gree_current_limit"
    device_class: "current"
    state_class: "measurement"
    address: 38
    register_type: holding
    value_type: U_WORD
    unit_of_measurement: 'A'   
        
  - platform: modbus_controller
    modbus_controller_id: versati3
    id: gree_status_unit_status
    name: "gree_unit_status"
    state_class: "measurement"
    address: 117
    register_type: holding
    value_type: U_WORD

  - platform: modbus_controller
    modbus_controller_id: versati3
    id: gree_status_t_outdoor
    name: "gree_status_t_outdoor"
    device_class: "temperature"
    state_class: "measurement"
    address: 118
    register_type: holding
    value_type: S_WORD
    accuracy_decimals: 1
    filters:
      - multiply: 0.1

    unit_of_measurement: '°C'   

  - platform: modbus_controller
    modbus_controller_id: versati3
    id: gree_status_t_water_out
    name: "gree_status_t_water_out"
    device_class: "temperature"
    state_class: "measurement"
    address: 125
    register_type: holding
    value_type: U_WORD
    accuracy_decimals: 1
    filters:
      - multiply: 0.1
    unit_of_measurement: '°C'   

  - platform: modbus_controller
    modbus_controller_id: versati3
    id: gree_status_t_water_in
    name: "gree_status_t_water_in"
    device_class: "temperature"
    state_class: "measurement"
    address: 127
    register_type: holding
    value_type: U_WORD
    accuracy_decimals: 1
    filters:
      - multiply: 0.1
    unit_of_measurement: '°C'   

  - platform: modbus_controller
    modbus_controller_id: versati3
    id: t_remote_room
    name: "gree_status_t_remote_room"
    device_class: "temperature"
    state_class: "measurement"
    address: 129
    register_type: holding
    value_type: U_WORD
    accuracy_decimals: 1
    filters:
      - multiply: 0.1
    unit_of_measurement: '°C'   

  - platform: modbus_controller
    modbus_controller_id: versati3
    id: gree_status_t_weather_depend
    name: "gree_status_t_weather_depend"
    device_class: "temperature"
    state_class: "measurement"
    address: 137
    register_type: holding
    value_type: U_WORD
    unit_of_measurement: '°C'   

  - platform: modbus_controller
    modbus_controller_id: versati3
    id: gree_status_setting_frequency
    name: "gree_status_setting_frequency"
    state_class: "measurement"
    address: 142
    register_type: holding
    value_type: U_WORD

  - platform: modbus_controller
    modbus_controller_id: versati3
    id: gree_status_running_frequency
    name: "gree_status_running_frequency"
    state_class: "measurement"
    address: 143
    register_type: holding
    value_type: U_WORD
